### ISSUE TITLE
[Task] HashTag 컴포넌트화 실패!

### ISSUE THREAD

**Issue by Do66i** [codestates/just-moment-trip#107]
### ISSUE
- Group:  `client`,
- Type:  `feature`
- Detail:  Makin HashTag Component !

<p align="center">🚨  실패할 가능성이 매우 높습니다 🚨</p>
<p align="center"><img src="https://user-images.githubusercontent.com/89396179/165916616-80a8fb4a-1d74-4fac-8258-3280d99e577a.jpeg" width="40%" height="40%" /></p>
<p align="center">🚨  도움이 절실히 필요합니다 🚨</p>

### TODO
1. [ ] Diary에서 data흐름 체크하기
2. [ ] Tag컴포넌트 만들기 전 간단한 input 기능이 있는 component 만들어서 적용시켜보기
3. [ ] Tag Component 구현하기
4. [ ] 적용 및 디버깅

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2d`
- Group : `client`
- Sprint: `Sprint1`
- Urgency: `High`
