### ISSUE TITLE
[Task] Development of the ability to attach photos to the diary

### ISSUE THREAD

**Issue by Do66i** [codestates/just-moment-trip#123]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Development of the ability to attach photos to the Diary

<p align="center">🚨  실패할 수 있는 확률이 높은 작업입니다 🚨<br/>
🚨  도움기옥 모아야함 🚨<br/>
<img src="https://user-images.githubusercontent.com/89396179/166192724-80066512-eb77-4257-9eda-c6875115e9ce.jpeg" width="50%" height="50%" />
</p>

### TODO
1. [ ] 이미지 파일 넣는 법 서치
2. [ ] 데이터 흐름 파악 및 로직 구성을 위해 노트에 적어보기
3. [ ] 어드벤스드인 만큼 시간분배 잘하기
4. [ ] 만약 소비하는 시간대비 아웃풋이 빠르게 나오지 않는다면 즉시 팀원들께 알리고 의논하기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1d`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
