### ISSUE TITLE
[Task]해시태그 PATCH요청 디버깅하기

### ISSUE THREAD

**Issue by HyunminChoi1997** [codestates/just-moment-trip#133]
### ISSUE
- Group: `server`
- Type:  `feature`
- Detail: patch요청 할때 중복 값이 허용되면서 hashtag테이블 값도 지워준다

### TODO
1. [ ] 해시태그 POST요청 한번 더 보기
2. [ ] PATCH요청할때 hashtag값들 추가는 해도 삭제는 하지 않기
3. [ ] 중복 값 한번 다시 확인하기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group :`server`
- Sprint: `Final Project`
- Urgency: `High`
