### ISSUE TITLE
[Task] Refectoring to Diary - 문윤미

### ISSUE THREAD

**Issue by Do66i** [codestates/just-moment-trip#40]
### ISSUE
- Group:  `client`
- Type: `refectoring`
- Detail: refectoring to Diary

### TODO
1. [ ] Diary page와 관련된 컴포넌트 체크
2. [ ] 폴더 및 컴포넌트 리뉴얼
3. [ ] 코드 구현 및 버그확인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 8h`
- Group : `client`
- Sprint: `Sprint 1`
- Urgency: `High`
