### ISSUE TITLE
[Task] Account & Diary Confirmation and correction

### ISSUE THREAD

**Issue by Do66i** [codestates/just-moment-trip#72]
### ISSUE
- Group:  `client`
- Type: `bug`, `feature`
- Detail: Account & Diary Bare Quest 기능 확인 및 수정

### TODO
1. [ ] AccountEdit.js 최종수정
2. [ ] Account & Diary 기능 확인 후 팀원들과 논의
3. [ ] 논의 후 필요한 기능 || 삭제할 기능 체크 후 수정

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Sprint: `Sprint1`
- Urgency: `Middle`
