### ISSUE TITLE
[Task] 💃 ONE DAY ONE HOUR HAPPY MAKIN STYLED COMPONENT 💃

### ISSUE THREAD

**Issue by Do66i** [codestates/just-moment-trip#73]
### ISSUE
- Group:  `client`
- Type: `feature`,`CSS`
- Detail: 💅  PO A(ccount)꾸 & D(iary)꾸 WER 💅

### TODO
1. [ ] Home에서 틀을 잡아준다.
2. [ ] D꾸를 프로토타입을 참고하여 기초적인 Style을 입힌다.
3. [ ] A꾸를 프로토타입을 참고하여 기초적인 Style을 입힌다.

💐 Deep한 Style은 Sprint 2때 하는걸로

### Estimated time
> Pick one
### Labels
- Estimated time: `7d - 1.5h`
- Group : `client`
- Sprint: `Sprint1
- Urgency: `Low`
